version: 2.1

jobs:
  test_3_1:
    docker:
      - image: cimg/python:3.1.0
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python example.py

  test_3_11:
    docker:
      - image: cimg/python:3.11.0
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python example.py

workflows:
  build_and_test:
    jobs:
      - test_3_1
      - test_3_11
