version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.10.7
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python example.py

workflows:
  build_and_test:
    jobs:
      - test
